---
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app-template.name" . }}-external-secret
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: "before-hook-creation"
    {{- with .Values.externalSecrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName }}
    kind: {{ .Values.externalSecrets.storeKind }}
  target:
    name: {{ include "app-template.name" . }}-secret
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        decodingStrategy: {{ .remoteRef.decodingStrategy | default $.Values.externalSecrets.defaultDecodingStrategy }}
        key: {{ .remoteRef.secretId }}
        property: {{ .remoteRef.secretKey }}
    {{- end }}
{{- end }}
